haddocking/arctic3d

benchmark/README.md
benchmark/execute_arctic_bm5.py

first draft of arctic3d exec script

---

src/arctic3d/modules/clustering.py
src/arctic3d/modules/interface_matrix.py
tests/test_clustering.py

converted distance to similarity

---

src/arctic3d/modules/clustering.py
tests/test_clustering.py

Closes #83 by creating more tests and splitting the clustering functions in more readable and generalised building blocks.

refactored clustering

---

src/arctic3d/modules/clustering.py

fixed output in clustering

---

src/arctic3d/cli.py

added warning

---

tests/test_interface_matrix.py

unlinked matrix

---

src/arctic3d/modules/interface_matrix.py

converted columns to strings

---

src/arctic3d/cli.py
src/arctic3d/modules/output.py
tests/test_output.py

added run_dir input argument

---

src/arctic3d/cli.py
src/arctic3d/modules/interface.py
src/arctic3d/modules/pdb.py
tests/test_pdb.py

Closes #91 by adding the possibility to specify in input the local path to a pdbrenum database.

Local pdb renum

---

requirements.txt
src/arctic3d/modules/interface_matrix.py
src/arctic3d/modules/pdb.py
tests/test_pdb.py

first draft of new renumbering logic

---

src/arctic3d/cli.py
src/arctic3d/modules/pdb.py
tests/test_pdb.py

added chain_to_use parameter

---

src/arctic3d/modules/pdb.py

added correct res key

---

requirements.txt
src/arctic3d/cli.py
src/arctic3d/modules/interface.py
src/arctic3d/modules/pdb.py
tests/golden_data/interface_data_P40202.json
tests/golden_data/pdb_data_P40202.json
tests/test_interface.py
tests/test_pdb.py

Implement offline mode

---

src/arctic3d/modules/output.py

saved json

---

src/arctic3d/cli.py
src/arctic3d/modules/interface.py
src/arctic3d/modules/pdb.py
tests/test_interface.py

Closes #125 by adding the "full" option to consider every information in the interface retrieval phase

Uniprot pdb chain interfaces

---

src/arctic3d/modules/clustering.py
src/arctic3d/modules/output.py

added more colors in seq plot

---

src/arctic3d/cli.py
src/arctic3d/modules/interface.py
tests/test_interface.py

substituted out_uniprot with out_partner

---

src/arctic3d/cli_localise.py

Closes #156 and improves the CLI overall

refactored arctic3d_localise

---

src/arctic3d/modules/clustering.py

Closes #152 : now the dendrogram is horizontal and the names of different interfaces are more readable

implemented horizontal dendrogram

---

README.md
src/arctic3d/cli_localise.py

added out_partner argument

---

src/arctic3d/cli.py
src/arctic3d/modules/cluster_interfaces.py
src/arctic3d/modules/clustering.py
tests/test_clustering.py

Closes #150 by adding linkage strategy and threshold to the command line interface

Add linkage threshold

---

src/arctic3d/cli_resclust.py

added comment to clarify residue_list

---

src/arctic3d/cli_resclust.py
src/arctic3d/modules/clustering.py
tests/test_cli_resclust.py

Add maxclust

---

src/arctic3d/cli_localise.py
src/arctic3d/modules/output.py

completed quickgo localisation

---

src/arctic3d/cli.py
src/arctic3d/modules/interface.py
src/arctic3d/modules/output.py
src/arctic3d/modules/pdb.py

minor adjustments

---

src/arctic3d/cli_resclust.py

adjusted threshold and improved docs

---

src/arctic3d/cli.py
src/arctic3d/cli_localise.py
src/arctic3d/cli_restraints.py

added process ID to cli and corrected logname

---

src/arctic3d/modules/pdb.py

reduced max_pdb_num to 10

---

src/arctic3d/__init__.py
src/arctic3d/cli.py
src/arctic3d/cli_localise.py
src/arctic3d/cli_resclust.py
src/arctic3d/cli_restraints.py
src/arctic3d/modules/log.py
src/arctic3d/modules/output.py
tests/test_cli.py
tests/test_cli_localise.py
tests/test_cli_restraints.py
tests/test_output.py

Closes #232 by using the same logic used by HADDOCK3

changed logging logic

---

src/arctic3d/cli.py

Store true

---

src/arctic3d/cli.py
src/arctic3d/modules/pdb.py
tests/golden_data/3psg_updated.cif
tests/golden_data/pdb3psg.pdb
tests/test_pdb.py

Ins code and mda

---

src/arctic3d/cli.py
src/arctic3d/modules/output.py

Correct calphas resnames

---

src/arctic3d/cli.py
src/arctic3d/modules/pdb.py
tests/test_cli.py
tests/test_pdb.py

Renumber interfaces

---

src/arctic3d/cli.py

allowed lowercase uniprot

---

src/arctic3d/cli.py
src/arctic3d/modules/pdb.py
tests/test_pdb.py

Closes #230 by returning the selected cif file in `get_maxint_pdb` and `get_best_pdb`

return cif file pdb functions

---

src/arctic3d/modules/clustering.py

Improve dendrogram

---

src/arctic3d/modules/pdb.py
tests/golden_data/pdb4xoj.pdb
tests/test_pdb.py

Closes #117 by removing the call to pdb-tools package and adding a patch

Selaltloc patch

---

src/arctic3d/cli_resclust.py

handled one retrieved residue

---

src/arctic3d/cli.py
src/arctic3d/modules/clustering.py
tests/test_cli.py
tests/test_clustering.py
tests/test_pdb.py

Filter clusters

---

src/arctic3d/cli.py
src/arctic3d/modules/output.py

added version in log

---

src/arctic3d/cli_localise.py

Prettier localise

---

src/arctic3d/modules/output.py
tests/test_output.py

handled duplicate labels in arctic3d-localise plots

---

src/arctic3d/modules/output.py
tests/test_output.py

changing max_lab_length to 60 chars

Duplicate labels issue

---

src/arctic3d/cli_resclust.py

Bug nchains resclust

---

src/arctic3d/modules/output.py

changed color list

---

.github/workflows/ci.yml

updated checkout to v4

---

.github/dependabot.yml

change update frequency to monthly for dependabot

monthly update

---

install_blast_deps.sh
poetry.lock

Closes #393 by fixing the BLAST version.

updated blast installation

---

README.md
install_blast_deps.sh

created db directory and added help messages

---

tests/test_pdb.py

corrected chain
